### ISSUE TITLE
[Feature Request]: Add wifi connection 

### ISSUE THREAD

**Issue by Supernatnat11** [MassOS-Linux/MassOS#40]
### Checklist

- [x] I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my feature request has not already been reported.
- [X] If I am suggesting the addition of a program, the program is free software and licensed under a [GPL-compatible license](https://www.gnu.org/licenses/license-list.html).

### Suggestion

Add wireless connection for pc without ethernet connection.

**Comment by TheSonicMaster** [comment]
Wi-Fi is supported on MassOS.

If you are having an issue related to Wi-Fi connectivity, please open a [bug report](https://github.com/MassOS-Linux/MassOS/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+), and describe your issue in as much detail as possible, including hardware details, network details and anything else you feel will be useful for debugging and solving the issue.

If you are suggesting a feature related to Wi-Fi, such as a program to help manage Wi-Fi connections or a specific missing Wi-Fi driver, please describe this clearly in your feature request.

**Comment by Supernatnat11** [comment]
I think it's an bug or that there was no such option. My computer detects my wifi usb key as a normal USB flash drive without storage. In the driver installation disc, there is no Linux option. I don't know if this is normal or if there are other drivers that can work.

**Comment by DanielMYT** [comment]
Moved to https://github.com/MassOS-Linux/MassOS/issues/41 and fixed.
